<?xml version="1.0" encoding="UTF-8"?><testrun name="TestTorneio" project="TorneioAV1" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="tests.TestTorneio" time="0.0">
    <testcase name="testGrupo" classname="tests.TestTorneio" time="0.0">
      <failure>java.lang.AssertionError: expected:&lt;2&gt; but was:&lt;3&gt;&#13;
	at junit@4.12/org.junit.Assert.fail(Assert.java:88)&#13;
	at junit@4.12/org.junit.Assert.failNotEquals(Assert.java:834)&#13;
	at junit@4.12/org.junit.Assert.assertEquals(Assert.java:645)&#13;
	at junit@4.12/org.junit.Assert.assertEquals(Assert.java:631)&#13;
	at TorneioAV1/tests.TestTorneio.testGrupo(TestTorneio.java:26)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at junit@4.12/org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at junit@4.12/org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at junit@4.12/org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at junit@4.12/org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at junit@4.12/org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at junit@4.12/org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at junit@4.12/org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at junit@4.12/org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at junit@4.12/org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at junit@4.12/org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at junit@4.12/org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at junit@4.12/org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at junit@4.12/org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at junit@4.12/org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="testDerrota" classname="tests.TestTorneio" time="0.0"/>
  </testsuite>
</testrun>
